# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "vkcv",
    #"ros1-publisher",
    #"ros1-gazebo",
    #"ros2-publisher",
    "ocvref",
]
