[package]
name = "ocvref"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = "0.66"
sysinfo = "0.24.6"
vkcv = { path = "../vkcv" }