[package]
name = "viewer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.20.1"
egui_extras = "0.20.0"
eframe = "0.20.1"
vkcv = { path = "../vkcv" }
anyhow = "1"
image = "0.24.5"